[package]
name = "gitclaim"
type = "bin"
authors = ["saleel"]
compiler_version = ">=0.34.0"

[dependencies]
zkemail = { tag = "v0.3.0", path = "../../zkemail.nr/lib", directory = "lib" }
string_search = { tag = "v0.2.0", git = "https://github.com/noir-lang/noir_string_search" }